server:
   port: 9527
   
spring:
   application:
      name: cloud-zuul-gateway
         
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: cloud-zuul-9527                #修改服务名称
    prefer-ip-address: true                             #访问路径显示IP地址

zuul:
  prefix: /wlg
  ignored-services: "*"
  routes:
    mydept.serviceId: cloud-dept
    mydept.path: /mydept/**

info:
  app.name: wuligang-cloud
  company.name: www.wuligang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$